name: "Release to public PyPI"
description: "Release library artifacts to public PyPI"

inputs:
  library-name:
    description: 'Name of the Python library'
    required: true
    type: string
  twine-token:
    description: 'Password to be used when uploading to private PyPI'
    required: true
    type: string
  python-version:
    description: 'Desired Python version for using twine'
    default: '3.10'
    required: false
    type: string

runs:
  using: "composite"
  steps:
  
     - name: "Set up Python"
       uses: actions/setup-python@v4
       with:
         python-version: ${{ env.MAIN_PYTHON_VERSION }}

     - name: "Install required dependencies"
       shell: bash
       run: |
         python -m pip install --upgrade pip
         python -m pip install twine

    - name: "Download the library artifacts from build-library step"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.library-name }}-artifacts
        path: ${{ inputs.library-name }}-artifacts

    - name: "Display the structure of downloaded files"
      run: ls -R

    - name: "Upload artifacts to private PyPi"
      run: |
        python -m twine upload --skip-existing ${{ inputs.library-name }}-artifacts/**/*.whl
        python -m twine upload --skip-existing ${{ inputs.library-name }}-artifacts/**/*.tar.gz
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ inputs.twine-token }}
