name: "Documentation deploy stable version"
description: "Deploy stable documentation to GitHub pages"

inputs:
  cname:
    description: 'The canonical name of the documentation website'
    required: true
    type: string
  version-config:
    description: 'Path to the JSON file specifying version configuration'
    default: 'release/version_mapper.json'
    required: false
    type: string
  token:
    description: "Required token for documentation deployment"
    required: true
    type: string
  python-version:
    description: 'Desired Python version'
    default: '3.10'
    required: false
    type: string

runs:
  using: "composite"
  steps:

    - name: "Checkout project in the GitHub Pages branch"
      uses: actions/checkout@v3
      with:
        ref: 'gh-pages'

    - name: "List gh-pages content"
      shell: bash
      run: ls -R

    - name: "Prepare destination folder"
      shell: bash
      run: |
        folder=release/${{ github.ref_name }}
        if [[ -d $folder ]]; then rm -rf $folder; fi 
        mkdir -p $folder

    - name: "Download the HTML documentation artifact in release/${{ github.ref_name }}"
      uses: actions/download-artifact@v3
      with:
        name: documentation-html
        path: release/${{ github.ref_name }}
  
    - name: "Setup Python ${{ inputs.python-version }}"
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Install system dependencies for updating version table"
      shell: bash
      run: |
        sudo apt-get install curl
        python -m pip install -U pip

    - name: "Get the version_mapper.py utility"
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/pyansys/actions/main/scripts/version-mapper.py -o version-mapper.py

    - name: "Update the version JSON file"
      shell: bash
      run: | 
        python version-mapper.py -cname ${{ inputs.cname }} -version ${{ github.ref_name }} -filename ${{ inputs.version-config }}

    - name: "Deploy stable documentation"
      uses: JamesIves/github-pages-deploy-action@v4.4.0                       
      with:                                                                   
        token: ${{ inputs.token }}                                    
        branch: gh-pages                                                      
        clean: false
        single-commit: true 
