name: "Release to GitHub"
description: "Release library artifacts to GitHub release page"

inputs:
  library-name:
    description: 'Name of the Python library'
    required: true
    type: string

runs:
  using: "composite"
  steps:
  
    - name: "Download the ${{ inputs.library-name }} artifacts from build-library step"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.library-name }}-artifacts
        path: ${{ inputs.library-name }}-artifacts

    - name: "Download {{ inputs.library-name }} HTML documentation"
      uses: actions/download-artifact@v3
      with:
        name: documentation-html
        path: documentation-html

    - name: "Zip HTML documentation"
      uses: vimtor/action-zip@v1
      with:
        files: documentation-html
        dest: documentation-html.zip

    - name: "Download {{ inputs.library-name }} PDF documentation"
      uses: actions/download-artifact@v3
      with:
        name: documentation-pdf
        path: documentation-pdf

    - name: "Display the structure of downloaded files"
      shell: bash
      run: ls -R

    - name: "Release to GitHub"
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ inputs.library-name }}/*.whl
          ${{ inputs.library-name }}/*.tar.gz
          documentation-html.zip
          documentation-pdf/*.pdf
