name: "Code style"
description: "Check code style using pre-commit"

inputs:
  python-version:
    description: 'Desired Python version for pre-commit'
    default: '3.10'
    required: false
    type: string

runs:
  using: "composite"
  steps:
  
    - name: "Install Git and clone project"
      uses: actions/checkout@v3
  
    - name: "Setup Python"
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ input.python-version }}
  
    - name: "Install pre-commit"
      shell: bash
      run: |
        python -m pip install --upgrade pip pre-commit
        pre-commit install
  
    - name: "Run pre-commit"
      shell: bash
      run: pre-commit run --all-files --show-diff-on-failure
