name: GitHub CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION : '3.10'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  label-syncer:
    name: Label syncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: Set labels
    needs: [label-syncer]
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

    - name: Label based on changed files
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: ''

    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'doc') || 
        startsWith(github.event.pull_request.head.ref, 'docs')
      with:
        labels: documentation

    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'maint') ||
        startsWith(github.event.pull_request.head.ref, 'no-ci') ||
        startsWith(github.event.pull_request.head.ref, 'ci')
      with:
        labels: maintenance

    - uses: actions-ecosystem/action-add-labels@v1
      if: startsWith(github.event.pull_request.head.ref, 'feat')
      with:
        labels: |
          enhancement

    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'fix') ||
        startsWith(github.event.pull_request.head.ref, 'patch')
      with:
        labels: bug

  commenter:
    runs-on: ubuntu-latest
    steps:
    - name: Suggest to add labels
      uses: peter-evans/create-or-update-comment@v2
      if: toJSON(github.event.pull_request.labels.*.name) == '{}'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Please add one of the following labels to add this contribution to the Release Notes :point_down:
          - [bug](https://github.com/pyansys/actions/pulls?q=label%3Abug+)
          - [documentation](https://github.com/pyansys/actions/pulls?q=label%3Adocumentation+)
          - [enhancement](https://github.com/pyansys/actions/pulls?q=label%3Aenhancement+)
          - [good first issue](https://github.com/pyansys/actions/pulls?q=label%3Agood+first+issue)
          - [maintenance](https://github.com/pyansys/actions/pulls?q=label%3Amaintenance+)
          - [release](https://github.com/pyansys/actions/pulls?q=label%3Arelease+)

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - name: "Run PyAnsys code style checks"
        uses: pyansys/actions/code-style@main

  doc-style:
    name: "Doc style"
    runs-on: ubuntu-latest
    steps:
      - name: "Run Ansys documentation style checks"
        uses: pyansys/actions/doc-style@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [code-style]
    runs-on: ubuntu-latest
    steps:

      - name: Install Git and clone project
        uses: actions/checkout@v3

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
