name: GitHub CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION : '3.10'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code-style:
    name: Run code style using pre-commit
    runs-on: ubuntu-latest
    steps:

      - name: Install Git and clone project
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip pre-commitpre-commit
          pre-commit install

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure


  release:
    name: Release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [style]
    runs-on: ubuntu-latest
  
    steps:

      - name: Install Git and clone project
        uses: actions/checkout@v3

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
